# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ecf2c6c44ef99e87e3e3cd91cc2af3070a358ad9c803befc6d51a4fe959fdeea3958a7d801dfd6dcf37cfd62d20d5dd8f5748a01a2551a24f2c156b88d87279

test:
  secret_key_base: 70f15a13a421f1666093a306abccabb05890b654bc561811c1346819d5a72521d7a78c93b405da386447490f4be0acdc36b5de57f00463da00af487e32f18bd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
